#undef RGBLED_NUM
#define RGBLED_NUM 2
#define RBGLIGHT_LED_MAP { 1, 0 }

#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_CHRISTMAS_STEP 1
